name: AntiBlocker
main: ankitmaharjan252\AntiBlocker\Main
version: 1.0.0
api: 1.13.1
authors: [ankitmaharjan252, AndreTheGamer]

commands:
 antiblocker:
  description: Allow op to block words
  permission: antiblocker.command.antiblocker
 
permissions:
 antiblocker.command.antiblocker:
  description: Allow op to block words
  default: op
  antiblocker.bypass:
  description: Allows players to bypass words blocking
  default: op
